attn: 'eager'
MCOT: True

sam2:
  seed: 323
  device: cuda:0
  sam2_checkpoint: /path/to/your/sam2.1-hiera-large/sam2.1_hiera_large.pt
  model_cfg: configs/sam2.1/sam2.1_hiera_l.yaml

dataset:
  m3cot:
    DATA_NAME: m3cot
    IMG_FOLDER: data_all/m3cot/images/
    EVAL_FILE: /path/to/data_all/test.jsonl

  scienceQA:
    DATA_NAME: scienceQA
    IMG_FOLDER: data_all/scienceQA/images/
    EVAL_FILE: ata_all/scienceQA/test.jsonl

  mme:
    DATA_NAME: mme
    IMG_FOLDER: data_all/mme/images/
    EVAL_FILE: data_all/mme/test.jsonl

model:
  qwen:
    model_path: /home/resource/model/Qwen2-VL-7B-Instruct
    prob_diff_threshold: 0.2
    num_selected_patches: 64

